
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lfg
    username: postgres
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver

lol:
  cache:
    minutes: 30
    size: 20000
  api:
    key: ${LOL_API_KEY}

google:
  cloud:
    messaging:
      server:
        id: ${GOOGLE_SERVER_ID}
        key: ${GOOGLE_MESSAGING_KEY}
  oauth:
    client:
      id: ${AUTH_CLIENT_ID}

